# GithubのメンションをSlackに通知するアクション（Github mention to Slack）
# https://github.com/marketplace/actions/github-mention-to-slack

name: "Github mention to Slack"
description: "Github mention to Slack"

inputs:
  repo-token:
    description: "Github access token to fetch .github/mention-to-slack.yml file."
    required: true
  slack-webhook-url:
    description: "Slack Incomming Webhook URL to notify."
    required: true

# 利用側は、通知するGithubアクションの設定として以下を設定
# https://docs.github.com/ja/actions/learn-github-actions/events-that-trigger-workflows
# on:
#   issues:
#     types: [opened, edited]
#   issue_comment:
#     # NOTE: `edited` 入れるとちょっとうるさいので off
#     types: [created]
#   pull_request:
#     # NOTE: `edited` 入れるとちょっとうるさいので off
#     types: [opened, review_requested]
#     branches-ignore:
#       - "release/**"
#   pull_request_review:
#     types: [submitted]
#   pull_request_review_comment:
#     types: [created, edited]

runs:
  using: composite
  steps:
    - name: Mention to slack
      uses: abeyuya/actions-mention-to-slack@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_TOLDEV }}
        configuration-path: mention-to-slack.yml
        icon-url: https://img.icons8.com/color/256/000000/github-2.png
        bot-name: "Githubお知らせ君"
        run-id: ${{ github.run_id }}
